### ISSUE TITLE
Błąd kwerendy 4 w "possibly a in A" vs. impossible

### ISSUE THREAD

**Issue by bartekx** [szwedor/RW-Grupa-1#15]
Zdania:
initially JestPaliwo and not Zepsuty
when Rozwazny Kieruje causes not JestPaliwo if not Zepsuty
impossible Kieruje if Zepsuty
impossible Mechanik Kieruje
when Mechanik Naprawia typically causes not Zepsuty if Zepsuty
observable Zepsuty after Nierozwazny Kieruje
when Nierozwazny Kieruje causes not JestPaliwo if not Zepsuty
JestPaliwo after Rozwazny Tankuje
JestPaliwo after Nierozwazny Tankuje

Kwerendy:
possibly Rozwazny in Mechanik Naprawia
possibly Mechanik in Nierozwazny Kieruje
possibly Mechanik in Kieruje
possibly Rozwazny in Rozwazny Kieruje
necessary Rozwazny in Rozwazny Kieruje
necessary Rozwazny in Nierozwazny Kieruje

Oczekiwany rezultat:
False
False
False
True
True
False

Aktualny rezultat:
False
False
True
True
True
False

**Comment by szwedor** [comment]
dzięki, nie bylo filtrowanie w jedym miejscu
